debug build output

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -28,22 +28,32 @@ jobs:
          cd apps/frontend
          npm ci
 
-      - name: Clean Nx cache
-        run: |
-          cd apps/frontend
-          npx nx clean
-
       - name: Build Angular app 🔧
         run: |
          cd apps/frontend
          npx nx build anx-store --configuration=production --base-href="/team-challenge-online-shop/"
-          # Check if the build output exists after the build process
-         ls -R dist/apps/anx-store
+          # Debug: Check if build output exists
+          echo "Listing the build output directory (dist)"
+          ls -R dist/
+          ls -R dist/apps/anx-store || echo "Build folder not found"
 
-       # Check if the build folder exists
+          # Step 2: List build directory contents
       - name: List build directory contents
         run: |
-          ls -R dist/apps/anx-store
+          # Debug: Check current working directory
+          echo "Current directory: $(pwd)"
+
+          # List the dist folder contents
+          echo "Listing contents of dist"
+          ls dist/
+
+           # List the apps folder
+          echo "Listing contents of dist/apps"
+          ls dist/apps/
+
+          # List the anx-store folder (if it exists)
+          echo "Listing contents of dist/apps/anx-store"
+          ls -R dist/apps/anx-store || echo "No contents found in dist/apps/anx-store"
 
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@releases/v3
